### ISSUE TITLE
About Us - Content

### ISSUE THREAD

**Issue by markjasondawson** [qcbt2016/qcbt2016.github.io#27]
I was thinking of separating the about us section into two main headers. What is QCBT? and Our Mission. I have written blurbs for each header.

What is QCBT?
QCBT stands for the Queen's Conference on Business and Technology. The conference tackles two subjects that are collectively shaping our world and the way we live. Over a two-day weekend, a group of talented and impactful students connect with industry leaders to progress themselves in both an academic and social sense. The format is fast-paced with 6 unique speaker stories, 2 corporate workshops, and 1 engaging case competition all over the course of a weekend. Bringing together 150 students from over 10 different schools around Canada, QCBT is a winning formula for curious minds to engage in meaningful content that will explore the business and technology space. 

Our mission:
We are building a community. An environment for students and industry alike to learn from each other. We aim for ideas to be spread, insights to be gained and connections to surface that will change perspectives. This weekend will create the opportunity for delegates to break into the business and technology field.

**Comment by harrylewis** [comment]
This has been added to the home page. For now, this will serve as the "About Us" page.
