### ISSUE TITLE
Sponsorship Blurb

### ISSUE THREAD

**Issue by markjasondawson** [qcbt2016/qcbt2016.github.io#30]
Blurb for current sponsors/sponsorship page:

We are passionate about creating a community that fosters mutually beneficial relationships between our sponsors and delegates. Participating with the Queen's Conference on Business and Technology is an opportunity to build relationships and inspire new ideas. The conference is possible by the generous support from our corporate partners and in return, we provide a forum for recruitment and company exposure that benefits everyone involved.

**Comment by harrylewis** [comment]
I shortened this pending approval. It is on the sponsorship page.
