### ISSUE TITLE
Current Sponsors Re-formatting

### ISSUE THREAD

**Issue by markjasondawson** [qcbt2016/qcbt2016.github.io#51]
The 4 newly added sponsors are too large/larger than accenture, ibm, etc. Potentially format like this - RBC and manulife large on top. Then a row of four under those. Then a row of 4 under those. Therefore Manulife/RBC width must be twice that of others.

Order sponsors like this as I feel it matters what people see first:
1st Row - Manulife and RBC 
2nd Row - Oracle, Dropbox, Couch & Associates, Dig
3rd Row - IBM, E&O, Accenture, Wealthsimple

**Comment by anthonyn60** [comment]
Can we also add a "Partners" section for QIC, the ECE dept, and (pending Dean's Donation) FEAS?

**Comment by harrylewis** [comment]
This has been completed.
